#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class BaseResp:
  """
  Attributes:
   - StatusMessage
   - StatusCode
   - Extra
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'StatusMessage', None, "", ), # 1
    (2, TType.I32, 'StatusCode', None, 0, ), # 2
    (3, TType.MAP, 'Extra', (TType.STRING,None,TType.STRING,None), None, ), # 3
  )

  def __init__(self, StatusMessage=thrift_spec[1][4], StatusCode=thrift_spec[2][4], Extra=None,):
    self.StatusMessage = StatusMessage
    self.StatusCode = StatusCode
    self.Extra = Extra

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.StatusMessage = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.StatusCode = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.MAP:
          self.Extra = {}
          (_ktype1, _vtype2, _size0 ) = iprot.readMapBegin()
          for _i4 in xrange(_size0):
            _key5 = iprot.readString();
            _val6 = iprot.readString();
            self.Extra[_key5] = _val6
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('BaseResp')
    if self.StatusMessage is not None:
      oprot.writeFieldBegin('StatusMessage', TType.STRING, 1)
      oprot.writeString(self.StatusMessage)
      oprot.writeFieldEnd()
    if self.StatusCode is not None:
      oprot.writeFieldBegin('StatusCode', TType.I32, 2)
      oprot.writeI32(self.StatusCode)
      oprot.writeFieldEnd()
    if self.Extra is not None:
      oprot.writeFieldBegin('Extra', TType.MAP, 3)
      oprot.writeMapBegin(TType.STRING, TType.STRING, len(self.Extra))
      for kiter7,viter8 in self.Extra.items():
        oprot.writeString(kiter7)
        oprot.writeString(viter8)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.StatusMessage)
    value = (value * 31) ^ hash(self.StatusCode)
    value = (value * 31) ^ hash(self.Extra)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
